sudo: false

language: node_js

node_js:
  - 6.10

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - npm i -g npm
  - npm i -g lerna@2.0.0-beta.38

before_script:
  - npm prune

script:
  - lerna bootstrap
  - npm run coverage
